use crate::{audit, config::Config, tmux};
use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    io::Read,
    path::{Path, PathBuf},
};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentSession {
    pub agent: String,
    pub session_id: String,
    #[serde(default)]
    pub server: String,
}

#[derive(Deserialize)]
struct HookInput {
    session_id: String,
}

pub fn install_hooks() -> Result<()> {
    let executable = env::current_exe().context("could not locate the automux executable")?;
    let home = env::var_os("HOME")
        .map(PathBuf::from)
        .context("HOME is not set")?;
    let mut installed = Vec::new();
    let mut installed_codex = false;

    if command_exists("nvim") {
        let config_home = env::var_os("XDG_CONFIG_HOME")
            .filter(|value| !value.is_empty())
            .map(PathBuf::from)
            .unwrap_or_else(|| home.join(".config"));
        let path = config_home.join("nvim/plugin/automux.lua");
        install_neovim_plugin(&path, &executable)?;
        installed.push(format!("Neovim ({})", path.display()));
    }
    if command_exists("claude") {
        let path = home.join(".claude/settings.json");
        install_hook(&path, "claude", &executable)?;
        installed.push(format!("Claude Code ({})", path.display()));
    }
    if command_exists("codex") {
        let path = home.join(".codex/hooks.json");
        install_hook(&path, "codex", &executable)?;
        installed.push(format!("Codex ({})", path.display()));
        installed_codex = true;
    }

    if installed.is_empty() {
        bail!("none of nvim, claude, or codex was found on PATH; nothing installed");
    }
    println!("installed or updated automux hooks for:");
    for item in installed {
        println!("  {item}");
    }
    if installed_codex {
        println!("Codex requires reviewing the new hook with /hooks before it will run.");
    }
    Ok(())
}

fn install_neovim_plugin(path: &Path, executable: &Path) -> Result<()> {
    if path.exists() {
        let existing = fs::read_to_string(path)?;
        if !existing.contains("automux-managed-neovim-plugin") {
            bail!(
                "{} already exists and is not managed by automux; it was not modified",
                path.display()
            );
        }
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let executable = serde_json::to_string(&executable.display().to_string())?;
    let plugin = format!(
        r#"-- automux-managed-neovim-plugin
-- Generated by `automux install-hooks`; edits may be replaced.
if not vim.env.TMUX_PANE then
  return
end

local pane = vim.env.TMUX_PANE:match("^%%(%d+)$")
if not pane then
  return
end

-- Pane IDs restart at %0 in every tmux server, so the state directory is
-- scoped per server. Ask automux for it rather than recomputing the key here.
local directory = vim.fn.system({{{executable}, "pane-dir"}})
if vim.v.shell_error ~= 0 then
  return
end
directory = vim.trim(directory)
if directory == "" then
  return
end
local session = directory .. "/pane-" .. pane .. ".vim"
local registration = directory .. "/pane-" .. pane .. ".json"

local server = vim.env.TMUX and vim.env.TMUX:match("^(.*),[^,]+$")
if server then
  local temporary = registration .. ".tmp"
  vim.fn.writefile({{ vim.json.encode({{ server = server }}) }}, temporary)
  os.rename(temporary, registration)
end

local pending = false
local function save_session()
  if pending then
    return
  end
  pending = true
  vim.defer_fn(function()
    pending = false
    if vim.v.exiting ~= vim.NIL then
      return
    end
    local temporary = session .. ".tmp"
    vim.cmd("silent! mksession! " .. vim.fn.fnameescape(temporary))
    os.rename(temporary, session)
  end, 250)
end

local group = vim.api.nvim_create_augroup("AutomuxSession", {{ clear = true }})
vim.api.nvim_create_autocmd(
  {{ "VimEnter", "SessionLoadPost", "BufWritePost", "TabNew", "TabClosed", "WinNew", "WinClosed", "DirChanged" }},
  {{ group = group, callback = save_session }}
)
vim.api.nvim_create_autocmd("VimLeavePre", {{
  group = group,
  callback = function()
    local temporary = session .. ".tmp"
    vim.cmd("silent! mksession! " .. vim.fn.fnameescape(temporary))
    os.rename(temporary, session)
    if server and vim.fn.filereadable(registration) == 1 then
      local registered = vim.json.decode(table.concat(vim.fn.readfile(registration), "\n"))
      if registered.server == server then
        os.remove(registration)
      end
    end
  end,
}})
"#
    );
    fs::write(path, plugin)?;
    Ok(())
}

pub fn register_agent(config: &Config, agent: &str, mut input: impl Read) -> Result<()> {
    validate_agent(agent)?;
    let Some((pane_number, server)) = tmux_context()? else {
        return Ok(());
    };
    let hook: HookInput = serde_json::from_reader(&mut input).context("invalid hook input")?;
    if hook.session_id.trim().is_empty() {
        bail!("hook input contained an empty session_id");
    }

    write_agent(config, &server, pane_number, agent, &hook.session_id)?;
    audit::record(
        config,
        "agent_registered",
        json!({"agent": agent, "session_id": hook.session_id, "pane": format!("%{pane_number}")}),
    );
    Ok(())
}

/// Record the agent session a restored pane was launched with.
///
/// The agents' own `SessionStart` hooks are the primary source of this
/// association, but they are outside automux's control: Codex, for example,
/// does not currently run them when a session is resumed, which silently drops
/// the session ID from the next snapshot and makes the resume work exactly
/// once. Automux knows which session it just launched, so it records that
/// directly; a hook firing afterwards simply overwrites it with the same or
/// newer value.
pub fn register_restored_agent(
    config: &Config,
    pane_number: u64,
    session: &AgentSession,
) -> Result<()> {
    let Some(server) = tmux::server_identity() else {
        return Ok(());
    };
    write_agent(
        config,
        &server,
        pane_number,
        &session.agent,
        &session.session_id,
    )
}

fn write_agent(
    config: &Config,
    server: &str,
    pane_number: u64,
    agent: &str,
    session_id: &str,
) -> Result<()> {
    let directory = server_dir(config, "agents", server)?;
    atomic_json(
        &directory.join(format!("pane-{pane_number}.json")),
        &AgentSession {
            agent: agent.to_owned(),
            session_id: session_id.to_owned(),
            server: server.to_owned(),
        },
    )
}

pub fn unregister_agent(config: &Config, agent: &str, mut input: impl Read) -> Result<()> {
    validate_agent(agent)?;
    let Some((pane_number, server)) = tmux_context()? else {
        return Ok(());
    };
    let hook: HookInput = serde_json::from_reader(&mut input).context("invalid hook input")?;
    let path = server_dir(config, "agents", &server)?.join(format!("pane-{pane_number}.json"));
    if !path.exists() {
        return Ok(());
    }
    let registered: AgentSession = serde_json::from_slice(&fs::read(&path)?)
        .with_context(|| format!("invalid JSON in {}", path.display()))?;
    if registered.agent == agent
        && registered.session_id == hook.session_id
        && registered.server == server
    {
        fs::remove_file(path)?;
        audit::record(
            config,
            "agent_unregistered",
            json!({"agent": agent, "session_id": hook.session_id, "pane": format!("%{pane_number}")}),
        );
    }
    Ok(())
}

/// Per-server state directory.
///
/// tmux reuses pane IDs from `%0` upwards in every new server, so a bare
/// `pane-N` name is not unique: a second server overwrites, and then deletes,
/// the first server's registration for the same pane number.
pub fn server_dir(config: &Config, kind: &str, server: &str) -> Result<PathBuf> {
    let directory = config.state_dir.join(kind).join(tmux::server_key(server));
    fs::create_dir_all(&directory)?;
    // The key is a hash, so the identity has to be stored to prune later.
    let marker = directory.join("server");
    if !marker.exists() {
        fs::write(marker, server)?;
    }
    Ok(directory)
}

/// Remove per-server state left behind by tmux servers that have exited.
pub fn prune_dead_servers(config: &Config, keep: &str) {
    let keep = tmux::server_key(keep);
    for kind in ["agents", "nvim", "history"] {
        let Ok(entries) = fs::read_dir(config.state_dir.join(kind)) else {
            continue;
        };
        for entry in entries.flatten() {
            if !entry.path().is_dir() || entry.file_name().to_string_lossy() == keep {
                continue;
            }
            let Ok(identity) = fs::read_to_string(entry.path().join("server")) else {
                continue;
            };
            if !tmux::server_alive(identity.trim()) {
                let _ = fs::remove_dir_all(entry.path());
            }
        }
    }
}

fn current_server_dir(config: &Config, kind: &str) -> Option<PathBuf> {
    let server = tmux::server_identity()?;
    server_dir(config, kind, &server).ok()
}

fn pane_files(directory: &Path) -> Vec<(u64, PathBuf)> {
    let Ok(entries) = fs::read_dir(directory) else {
        return Vec::new();
    };
    entries
        .flatten()
        .filter_map(|entry| {
            let number = entry
                .file_name()
                .to_str()?
                .strip_prefix("pane-")?
                .strip_suffix(".json")?
                .parse::<u64>()
                .ok()?;
            Some((number, entry.path()))
        })
        .collect()
}

pub fn registry(config: &Config) -> Result<BTreeMap<String, AgentSession>> {
    let mut registry = BTreeMap::new();
    let Some(directory) = current_server_dir(config, "agents") else {
        return Ok(registry);
    };
    for (number, path) in pane_files(&directory) {
        let session: AgentSession = serde_json::from_slice(&fs::read(&path)?)
            .with_context(|| format!("invalid JSON in {}", path.display()))?;
        registry.insert(format!("%{number}"), session);
    }
    Ok(registry)
}

/// Legacy, pre-scoping Neovim registration, written directly into `nvim/`.
#[derive(Deserialize)]
struct NvimRegistration {
    server: String,
}

pub fn nvim_registry(config: &Config) -> Result<BTreeSet<String>> {
    let mut registry = BTreeSet::new();
    let Some(server) = tmux::server_identity() else {
        return Ok(registry);
    };
    // A Neovim still running the pre-scoping plugin writes into `nvim/` itself
    // and tags the file with its server, so honour both layouts until every
    // instance has been restarted.
    for (number, path) in pane_files(&config.state_dir.join("nvim")) {
        let legacy: NvimRegistration = match fs::read(&path) {
            Ok(data) => match serde_json::from_slice(&data) {
                Ok(value) => value,
                Err(_) => continue,
            },
            Err(_) => continue,
        };
        if legacy.server == server {
            registry.insert(format!("%{number}"));
        }
    }
    for (number, _) in pane_files(&server_dir(config, "nvim", &server)?) {
        registry.insert(format!("%{number}"));
    }
    Ok(registry)
}

/// Directory the Neovim plugin keeps its per-pane session and registration in.
pub fn print_pane_dir(config: &Config) -> Result<()> {
    let server = tmux::server_identity().context("not running inside tmux")?;
    println!("{}", server_dir(config, "nvim", &server)?.display());
    Ok(())
}

fn install_hook(path: &Path, agent: &str, executable: &Path) -> Result<()> {
    let mut root: Value = if path.exists() {
        serde_json::from_slice(&fs::read(path)?)
            .with_context(|| format!("{} is not valid JSON; it was not modified", path.display()))?
    } else {
        json!({})
    };
    merge_hook(&mut root, agent, executable)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    atomic_json(path, &root)
}

fn merge_hook(root: &mut Value, agent: &str, executable: &Path) -> Result<()> {
    let object = root
        .as_object_mut()
        .context("hook configuration root must be an object")?;
    let hooks = object.entry("hooks").or_insert_with(|| json!({}));
    let hooks = hooks
        .as_object_mut()
        .context("the hooks setting must be an object")?;
    merge_event_hook(
        hooks,
        "SessionStart",
        Some("startup|resume|clear|fork"),
        "register-agent",
        agent,
        executable,
    )?;
    merge_event_hook(
        hooks,
        "SessionEnd",
        None,
        "unregister-agent",
        agent,
        executable,
    )?;
    Ok(())
}

fn merge_event_hook(
    hooks: &mut serde_json::Map<String, Value>,
    event: &str,
    matcher: Option<&str>,
    action: &str,
    agent: &str,
    executable: &Path,
) -> Result<()> {
    let groups = hooks.entry(event).or_insert_with(|| json!([]));
    let groups = groups
        .as_array_mut()
        .with_context(|| format!("hooks.{event} must be an array"))?;
    groups.retain(|group| !contains_automux_hook(group, action, agent));
    let command = format!(
        "{} {action} {agent}",
        shell_quote(&executable.display().to_string())
    );
    let mut group = json!({
        "hooks": [{
            "type": "command",
            "command": command,
            "timeout": if event == "SessionEnd" { 3 } else { 5 }
        }]
    });
    if let Some(matcher) = matcher {
        group["matcher"] = Value::String(matcher.to_owned());
    }
    groups.push(group);
    Ok(())
}

fn contains_automux_hook(group: &Value, action: &str, agent: &str) -> bool {
    group
        .get("hooks")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(|hook| hook.get("command").and_then(Value::as_str))
        .any(|command| {
            command.contains("automux") && command.contains(action) && command.ends_with(agent)
        })
}

fn validate_agent(agent: &str) -> Result<()> {
    if !matches!(agent, "claude" | "codex") {
        bail!("unsupported agent {agent:?}; expected claude or codex");
    }
    Ok(())
}

fn tmux_context() -> Result<Option<(u64, String)>> {
    let Some(pane) = env::var_os("TMUX_PANE") else {
        return Ok(None);
    };
    let pane_number = pane
        .to_string_lossy()
        .strip_prefix('%')
        .and_then(|value| value.parse::<u64>().ok())
        .context("TMUX_PANE did not contain a valid tmux pane ID")?;
    let server = server_identity().context("TMUX did not identify the current tmux server")?;
    Ok(Some((pane_number, server)))
}

fn server_identity() -> Option<String> {
    env::var("TMUX")
        .ok()
        .and_then(|value| value.rsplit_once(',').map(|(server, _)| server.to_owned()))
}

fn command_exists(name: &str) -> bool {
    env::var_os("PATH")
        .map(|path| env::split_paths(&path).any(|dir| dir.join(name).is_file()))
        .unwrap_or(false)
}

fn atomic_json(path: &Path, value: &impl Serialize) -> Result<()> {
    let tmp = path.with_extension("json.tmp");
    fs::write(&tmp, serde_json::to_vec_pretty(value)?)?;
    fs::rename(tmp, path)?;
    Ok(())
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn merge_preserves_other_hooks_and_is_idempotent() {
        let mut value = json!({
            "theme": "dark",
            "hooks": {
                "SessionStart": [{
                    "matcher": "startup",
                    "hooks": [{"type": "command", "command": "other-hook"}]
                }]
            }
        });
        let executable = Path::new("/tmp/automux test/bin");

        merge_hook(&mut value, "claude", executable).unwrap();
        merge_hook(&mut value, "claude", executable).unwrap();

        assert_eq!(value["theme"], "dark");
        let starts = value["hooks"]["SessionStart"].as_array().unwrap();
        assert_eq!(starts.len(), 2);
        assert_eq!(starts[0]["hooks"][0]["command"], "other-hook");
        assert_eq!(
            starts[1]["hooks"][0]["command"],
            "'/tmp/automux test/bin' register-agent claude"
        );
        let ends = value["hooks"]["SessionEnd"].as_array().unwrap();
        assert_eq!(ends.len(), 1);
        assert_eq!(
            ends[0]["hooks"][0]["command"],
            "'/tmp/automux test/bin' unregister-agent claude"
        );
    }

    #[test]
    fn neovim_plugin_is_idempotent_and_protects_unmanaged_files() {
        let temp = tempfile::tempdir().unwrap();
        let path = temp.path().join("plugin/automux.lua");
        let executable = Path::new("/tmp/automux test/bin");

        install_neovim_plugin(&path, executable).unwrap();
        let first = fs::read_to_string(&path).unwrap();
        install_neovim_plugin(&path, executable).unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), first);
        assert!(first.contains("pane-"));
        assert!(first.contains("pane-dir"));
        assert!(first.contains("registration"));
        assert!(
            first.contains("'/tmp/automux test/bin'")
                || first.contains("\"/tmp/automux test/bin\"")
        );

        fs::write(&path, "-- user-owned file\n").unwrap();
        assert!(install_neovim_plugin(&path, executable).is_err());
        assert_eq!(fs::read_to_string(path).unwrap(), "-- user-owned file\n");
    }
}
