use crate::config::Config;
use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    io::Read,
    path::{Path, PathBuf},
};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentSession {
    pub agent: String,
    pub session_id: String,
    #[serde(default)]
    pub server: String,
}

#[derive(Deserialize)]
struct HookInput {
    session_id: String,
}

pub fn install_hooks() -> Result<()> {
    let executable = env::current_exe().context("could not locate the automux executable")?;
    let home = env::var_os("HOME")
        .map(PathBuf::from)
        .context("HOME is not set")?;
    let mut installed = Vec::new();
    let mut installed_codex = false;

    if command_exists("nvim") {
        let config_home = env::var_os("XDG_CONFIG_HOME")
            .filter(|value| !value.is_empty())
            .map(PathBuf::from)
            .unwrap_or_else(|| home.join(".config"));
        let path = config_home.join("nvim/plugin/automux.lua");
        install_neovim_plugin(&path, &executable)?;
        installed.push(format!("Neovim ({})", path.display()));
    }
    if command_exists("claude") {
        let path = home.join(".claude/settings.json");
        install_hook(&path, "claude", &executable)?;
        installed.push(format!("Claude Code ({})", path.display()));
    }
    if command_exists("codex") {
        let path = home.join(".codex/hooks.json");
        install_hook(&path, "codex", &executable)?;
        installed.push(format!("Codex ({})", path.display()));
        installed_codex = true;
    }

    if installed.is_empty() {
        bail!("none of nvim, claude, or codex was found on PATH; nothing installed");
    }
    println!("installed or updated automux hooks for:");
    for item in installed {
        println!("  {item}");
    }
    if installed_codex {
        println!("Codex requires reviewing the new hook with /hooks before it will run.");
    }
    Ok(())
}

fn install_neovim_plugin(path: &Path, executable: &Path) -> Result<()> {
    if path.exists() {
        let existing = fs::read_to_string(path)?;
        if !existing.contains("automux-managed-neovim-plugin") {
            bail!(
                "{} already exists and is not managed by automux; it was not modified",
                path.display()
            );
        }
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let executable = serde_json::to_string(&executable.display().to_string())?;
    let plugin = format!(
        r#"-- automux-managed-neovim-plugin
-- Generated by `automux install-hooks`; edits may be replaced.
if not vim.env.TMUX_PANE then
  return
end

local pane = vim.env.TMUX_PANE:match("^%%(%d+)$")
if not pane then
  return
end

local state = vim.fn.system({{{executable}, "state-dir"}})
if vim.v.shell_error ~= 0 then
  return
end
state = vim.trim(state)
local directory = state .. "/nvim"
local session = directory .. "/pane-" .. pane .. ".vim"
local registration = directory .. "/pane-" .. pane .. ".json"
vim.fn.mkdir(directory, "p")

local server = vim.env.TMUX and vim.env.TMUX:match("^(.*),[^,]+$")
if server then
  local temporary = registration .. ".tmp"
  vim.fn.writefile({{ vim.json.encode({{ server = server }}) }}, temporary)
  os.rename(temporary, registration)
end

local pending = false
local function save_session()
  if pending then
    return
  end
  pending = true
  vim.defer_fn(function()
    pending = false
    if vim.v.exiting ~= vim.NIL then
      return
    end
    local temporary = session .. ".tmp"
    vim.cmd("silent! mksession! " .. vim.fn.fnameescape(temporary))
    os.rename(temporary, session)
  end, 250)
end

local group = vim.api.nvim_create_augroup("AutomuxSession", {{ clear = true }})
vim.api.nvim_create_autocmd(
  {{ "VimEnter", "SessionLoadPost", "BufWritePost", "TabNew", "TabClosed", "WinNew", "WinClosed", "DirChanged" }},
  {{ group = group, callback = save_session }}
)
vim.api.nvim_create_autocmd("VimLeavePre", {{
  group = group,
  callback = function()
    local temporary = session .. ".tmp"
    vim.cmd("silent! mksession! " .. vim.fn.fnameescape(temporary))
    os.rename(temporary, session)
    if server and vim.fn.filereadable(registration) == 1 then
      local registered = vim.json.decode(table.concat(vim.fn.readfile(registration), "\n"))
      if registered.server == server then
        os.remove(registration)
      end
    end
  end,
}})
"#
    );
    fs::write(path, plugin)?;
    Ok(())
}

pub fn register_agent(config: &Config, agent: &str, mut input: impl Read) -> Result<()> {
    validate_agent(agent)?;
    let Some((pane_number, server)) = tmux_context()? else {
        return Ok(());
    };
    let hook: HookInput = serde_json::from_reader(&mut input).context("invalid hook input")?;
    if hook.session_id.trim().is_empty() {
        bail!("hook input contained an empty session_id");
    }

    let directory = config.state_dir.join("agents");
    fs::create_dir_all(&directory)?;
    atomic_json(
        &directory.join(format!("pane-{pane_number}.json")),
        &AgentSession {
            agent: agent.to_owned(),
            session_id: hook.session_id,
            server,
        },
    )
}

pub fn unregister_agent(config: &Config, agent: &str, mut input: impl Read) -> Result<()> {
    validate_agent(agent)?;
    let Some((pane_number, server)) = tmux_context()? else {
        return Ok(());
    };
    let hook: HookInput = serde_json::from_reader(&mut input).context("invalid hook input")?;
    let path = config
        .state_dir
        .join("agents")
        .join(format!("pane-{pane_number}.json"));
    if !path.exists() {
        return Ok(());
    }
    let registered: AgentSession = serde_json::from_slice(&fs::read(&path)?)
        .with_context(|| format!("invalid JSON in {}", path.display()))?;
    if registered.agent == agent
        && registered.session_id == hook.session_id
        && registered.server == server
    {
        fs::remove_file(path)?;
    }
    Ok(())
}

pub fn registry(config: &Config) -> Result<BTreeMap<String, AgentSession>> {
    let directory = config.state_dir.join("agents");
    let mut registry = BTreeMap::new();
    if !directory.exists() {
        return Ok(registry);
    }
    let Some(server) = server_identity() else {
        return Ok(registry);
    };
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let name = entry.file_name();
        let Some(number) = name
            .to_str()
            .and_then(|name| name.strip_prefix("pane-"))
            .and_then(|name| name.strip_suffix(".json"))
            .and_then(|number| number.parse::<u64>().ok())
        else {
            continue;
        };
        let session: AgentSession = serde_json::from_slice(&fs::read(entry.path())?)
            .with_context(|| format!("invalid JSON in {}", entry.path().display()))?;
        if session.server == server {
            registry.insert(format!("%{number}"), session);
        }
    }
    Ok(registry)
}

#[derive(Deserialize)]
struct NvimRegistration {
    server: String,
}

pub fn nvim_registry(config: &Config) -> Result<BTreeSet<String>> {
    let directory = config.state_dir.join("nvim");
    let mut registry = BTreeSet::new();
    if !directory.exists() {
        return Ok(registry);
    }
    let Some(server) = server_identity() else {
        return Ok(registry);
    };
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let name = entry.file_name();
        let Some(number) = name
            .to_str()
            .and_then(|name| name.strip_prefix("pane-"))
            .and_then(|name| name.strip_suffix(".json"))
            .and_then(|number| number.parse::<u64>().ok())
        else {
            continue;
        };
        let registration: NvimRegistration = serde_json::from_slice(&fs::read(entry.path())?)
            .with_context(|| format!("invalid JSON in {}", entry.path().display()))?;
        if registration.server == server {
            registry.insert(format!("%{number}"));
        }
    }
    Ok(registry)
}

fn install_hook(path: &Path, agent: &str, executable: &Path) -> Result<()> {
    let mut root: Value = if path.exists() {
        serde_json::from_slice(&fs::read(path)?)
            .with_context(|| format!("{} is not valid JSON; it was not modified", path.display()))?
    } else {
        json!({})
    };
    merge_hook(&mut root, agent, executable)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    atomic_json(path, &root)
}

fn merge_hook(root: &mut Value, agent: &str, executable: &Path) -> Result<()> {
    let object = root
        .as_object_mut()
        .context("hook configuration root must be an object")?;
    let hooks = object.entry("hooks").or_insert_with(|| json!({}));
    let hooks = hooks
        .as_object_mut()
        .context("the hooks setting must be an object")?;
    merge_event_hook(
        hooks,
        "SessionStart",
        Some("startup|resume|clear|fork"),
        "register-agent",
        agent,
        executable,
    )?;
    merge_event_hook(
        hooks,
        "SessionEnd",
        None,
        "unregister-agent",
        agent,
        executable,
    )?;
    Ok(())
}

fn merge_event_hook(
    hooks: &mut serde_json::Map<String, Value>,
    event: &str,
    matcher: Option<&str>,
    action: &str,
    agent: &str,
    executable: &Path,
) -> Result<()> {
    let groups = hooks.entry(event).or_insert_with(|| json!([]));
    let groups = groups
        .as_array_mut()
        .with_context(|| format!("hooks.{event} must be an array"))?;
    groups.retain(|group| !contains_automux_hook(group, action, agent));
    let command = format!(
        "{} {action} {agent}",
        shell_quote(&executable.display().to_string())
    );
    let mut group = json!({
        "hooks": [{
            "type": "command",
            "command": command,
            "timeout": if event == "SessionEnd" { 3 } else { 5 }
        }]
    });
    if let Some(matcher) = matcher {
        group["matcher"] = Value::String(matcher.to_owned());
    }
    groups.push(group);
    Ok(())
}

fn contains_automux_hook(group: &Value, action: &str, agent: &str) -> bool {
    group
        .get("hooks")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(|hook| hook.get("command").and_then(Value::as_str))
        .any(|command| {
            command.contains("automux") && command.contains(action) && command.ends_with(agent)
        })
}

fn validate_agent(agent: &str) -> Result<()> {
    if !matches!(agent, "claude" | "codex") {
        bail!("unsupported agent {agent:?}; expected claude or codex");
    }
    Ok(())
}

fn tmux_context() -> Result<Option<(u64, String)>> {
    let Some(pane) = env::var_os("TMUX_PANE") else {
        return Ok(None);
    };
    let pane_number = pane
        .to_string_lossy()
        .strip_prefix('%')
        .and_then(|value| value.parse::<u64>().ok())
        .context("TMUX_PANE did not contain a valid tmux pane ID")?;
    let server = server_identity().context("TMUX did not identify the current tmux server")?;
    Ok(Some((pane_number, server)))
}

fn server_identity() -> Option<String> {
    env::var("TMUX")
        .ok()
        .and_then(|value| value.rsplit_once(',').map(|(server, _)| server.to_owned()))
}

fn command_exists(name: &str) -> bool {
    env::var_os("PATH")
        .map(|path| env::split_paths(&path).any(|dir| dir.join(name).is_file()))
        .unwrap_or(false)
}

fn atomic_json(path: &Path, value: &impl Serialize) -> Result<()> {
    let tmp = path.with_extension("json.tmp");
    fs::write(&tmp, serde_json::to_vec_pretty(value)?)?;
    fs::rename(tmp, path)?;
    Ok(())
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn merge_preserves_other_hooks_and_is_idempotent() {
        let mut value = json!({
            "theme": "dark",
            "hooks": {
                "SessionStart": [{
                    "matcher": "startup",
                    "hooks": [{"type": "command", "command": "other-hook"}]
                }]
            }
        });
        let executable = Path::new("/tmp/automux test/bin");

        merge_hook(&mut value, "claude", executable).unwrap();
        merge_hook(&mut value, "claude", executable).unwrap();

        assert_eq!(value["theme"], "dark");
        let starts = value["hooks"]["SessionStart"].as_array().unwrap();
        assert_eq!(starts.len(), 2);
        assert_eq!(starts[0]["hooks"][0]["command"], "other-hook");
        assert_eq!(
            starts[1]["hooks"][0]["command"],
            "'/tmp/automux test/bin' register-agent claude"
        );
        let ends = value["hooks"]["SessionEnd"].as_array().unwrap();
        assert_eq!(ends.len(), 1);
        assert_eq!(
            ends[0]["hooks"][0]["command"],
            "'/tmp/automux test/bin' unregister-agent claude"
        );
    }

    #[test]
    fn neovim_plugin_is_idempotent_and_protects_unmanaged_files() {
        let temp = tempfile::tempdir().unwrap();
        let path = temp.path().join("plugin/automux.lua");
        let executable = Path::new("/tmp/automux test/bin");

        install_neovim_plugin(&path, executable).unwrap();
        let first = fs::read_to_string(&path).unwrap();
        install_neovim_plugin(&path, executable).unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), first);
        assert!(first.contains("pane-"));
        assert!(first.contains("registration"));
        assert!(
            first.contains("'/tmp/automux test/bin'")
                || first.contains("\"/tmp/automux test/bin\"")
        );

        fs::write(&path, "-- user-owned file\n").unwrap();
        assert!(install_neovim_plugin(&path, executable).is_err());
        assert_eq!(fs::read_to_string(path).unwrap(), "-- user-owned file\n");
    }
}
